Repository facebookresearch/nle, pull requests merged in 2020-06, with the labels that each got.

#32 Set clang as linker on MacOS
  sys/unix/hints/macosx-nle
Labels: CLA Signed, bug, installation

#34 [in-repo] Deploy pip package and docker images on release
  .github/release-drafter.yml
  .github/workflows/build_docker.yml
  .github/workflows/pr-labeler.yml
  .github/workflows/test_and_deploy.yml
  .github/workflows/test_docker.yml
  docker/Dockerfile
  docker/README.md
Labels: CLA Signed, chore

#36 Remove unnecessary check in CI
  .github/workflows/build_docker.yml
Labels: CI, CLA Signed, bug

#37 Bump version.txt to v0.1.2
  version.txt
Labels: CLA Signed

#39 Add arXiv link and update bib
  README.md
Labels: CLA Signed, chore

#40 Define a new penalty_mode, "always", and make it the default.
  nle/env/tasks.py
Labels: CLA Signed

#42 Attempt to fix #41: "smooth quitting of game failed".
  nle/env/base.py
Labels: CLA Signed
