Repository facebookresearch/nle, pull requests merged in 2020-05, with the labels that each got.

#3 Implement PyPI daily workflow and artefacts generation
  .github/workflows/test_and_deploy.yml
  .github/workflows/test_package.yml
Labels: CI, CLA Signed

#7 Fix action selection in play script for nethack mode
  nle/scripts/play.py
Labels: CLA Signed

#9 Clear up installation instructions
  README.md
Labels: CLA Signed, documentation, installation

#4 Add linux dockerfiles, patch compilation for older g++ versions
  .github/workflows/test_docker.yml
  README.md
  docker/Dockerfile-bionic
  docker/Dockerfile-xenial
  docker/README.md
  sys/unix/hints/linux
Labels: CLA Signed, docker, enhancement, installation

#12 Add some workflows for automatic PR management
  .github/pr-labeler.yml
  .github/release-drafter.yml
  .github/workflows/pr-labeler.yml
  .github/workflows/release-drafter.yml
Labels: CLA Signed, chore, skip changelog

#13 Bump NLE to v0.1.1
  version.txt
Labels: CLA Signed, skip changelog

#14 Adding a related Minecraft environment
  README.md
Labels: CLA Signed

#17 Use raw image URLs for PyPI compatibility
  README.md
Labels: CLA Signed, chore

#18 Disable E402 for imports in agent.py
  nle/agent/agent.py
Labels: CLA Signed, bug

#19 Fix play script when using human mode with raw nethack
  nle/scripts/play.py
Labels: CLA Signed, bug

#16 update plot.py with examples and utility fixes
  nle/scripts/plot.py
Labels: CLA Signed, docs, enhancement

#22 Add savedir / archivefile flags to play script
  nle/scripts/play.py
Labels: CLA Signed, enhancement

#24 Do step check outside of _is_episode_end
  nle/env/base.py
  nle/env/tasks.py
Labels: CLA Signed, bug

#27 Update minimist to latest version
  nle/dashboard/package-lock.json
Labels: CLA Signed, chore

#29 Explicitly ask for clang in hints/macosx.
  sys/unix/hints/macosx
Labels: CLA Signed, bug, installation
