Repository facebookresearch/nle, pull requests merged in 2020-07, with the labels that each got.

#43 Clone repository recursively in CI when building docker images
  .github/workflows/build_docker.yml
  docker/Dockerfile
  docker/Dockerfile-xenial
Labels: CI, CLA Signed, bug, docker

#45 Install HACKDIR into package
  .gitignore
  CMakeLists.txt
  README.md
  doc/nle/source/getting_started.rst
  docker/README.md
  nle/nethack/nethack.py
  setup.py
Labels: CLA Signed, enhancement, installation

#50 Use nethack.MAX_GLYPH instead of magic constant.
  nle/agent/agent.py
Labels: CLA Signed

#52 Fix lodash version due to GHSA-p6mc-m468-83gw.
  nle/dashboard/package-lock.json
Labels: CLA Signed

#51 Create temporal ttyrecs inside temporal HACKDIR.
  nle/nethack/nethack.py
Labels: CLA Signed

#54 Require cmake version >= 3.14
  CMakeLists.txt
Labels: CLA Signed

#55 Update helpers
  nle/env/tasks.py
  nle/tests/test_nethack.py
  win/rl/helper.cc
Labels: CLA Signed

#56 Enable chars, colors, specials as observation tensors.
  nle/env/base.py
  nle/tests/test_envs.py
Labels: CLA Signed

#57 Bump version to 0.2.0.
  version.txt
Labels: CLA Signed
